### ISSUE TITLE
 Fira Code Nerd Font is broken

### ISSUE THREAD

**Issue by Puccet** [blinksh/fonts#23] opened 2020-09-14 21:20 UTC
It seems like this font is broken, if you choose it in the settings it does not work.

**Comment by ionut-maxim** [comment] 2021-11-27 10:56
Looks like the problem is fixed in https://github.com/blinksh/fonts/pull/22/files but it wasn't merged yet...

**Comment by Puccet** [comment] 2021-11-27 12:16
Good to know, when it will be available?

**Comment by thegcat** [comment] 2023-09-02 15:36
This should be fixed by #22 and could probably be closed.

**Closed** 2023-09-03 04:50 UTC
